probes:
  ReplicasHighProbe:
    alias: kube-znn.replicasHigh.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "replicasHigh"
      args.3: "count(kube_pod_container_info{image=\"cmendes/znn:600k\"})"
  
   
  ReplicasLowProbe:
    alias: kube-znn.replicasLow.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "replicasLow"
      args.3: "count(kube_pod_container_info{image=\"cmendes/znn:200k\"})"

  ReplicasTextProbe:
    alias: kube-znn.replicasText.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "replicasText"
      args.3: "count(kube_pod_container_info{image=\"cmendes/znn:text\"})"

  SloProbe:
    alias: kube-znn.slo.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "slo"
      args.3: "sum(rate(request_duration_seconds_bucket{le=\"00.010\"}[30s])) / sum(rate(request_duration_seconds_count[30s]))"

  TrafficProbe:
    alias: kube-znn.traffic.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "traffic"
      args.3: "sum (rate(nginx_ingress_nginx_http_requests_total{class=\"nginx\"}[30s]))"

  StabilityProbe:
    alias: kube-znn.stability.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "stability"
      args.3: "round(delta(kube_deployment_status_observed_generation{deployment=\"kube-znn\"}[30s]))"

  DeploymentPropertiesProbe:
    alias: deployments.default.kube-znn.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.DeploymentInfoProbe
      period: 5000
      args.length: 2
      args.0: "default"
      args.1: "kube-znn"
